### ISSUE TITLE
Issue with showing GIOPS Daily Forecast 3D - Polar Stereographic

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/configurations#4]
At present we are having issue with displaying this dataset. The log indicates an issue with the variables being indexed. We will need to look at the datasets to see if possibly there is a depth versus deptht.

**Comment by nsoontie** [comment]
Is it possible to copy the relevant errors from the log file to this dialogue? That might be helpful for future reference.

**Comment by dwayne-hart** [comment]
```
[2020-08-26 20:41:05 -0230] [4131] [ERROR] Error handling request /api/v1.0/tiles/gaussian/25/10/EPSG:3857/giops_day/votemper/2230416000/0/-5,30/4/6/6.png
Traceback (most recent call last):
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/Ocean-Data-Map-Project/routes/api_v1_0.py", line 785, in tile_v1_0
    'scale': scale,
  File "/home/ubuntu/Ocean-Data-Map-Project/plotting/tile.py", line 186, in plot
    args.get('neighbours')
  File "/home/ubuntu/Ocean-Data-Map-Project/data/model.py", line 122, in get_area
    latitude, longitude, depth, variable, time, return_depth=return_depth
  File "/home/ubuntu/Ocean-Data-Map-Project/data/mercator.py", line 268, in get_point
    data.values,
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataarray.py", line 407, in values
    return self.variable.values
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/variable.py", line 387, in values
    return _as_array_or_item(self._data)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/variable.py", line 208, in _as_array_or_item
    data = np.asarray(data)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/array/core.py", line 1047, in __array__
    x = self.compute()
 File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/array/core.py", line 81, in getter
    c = np.asarray(c)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/indexing.py", line 610, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/indexing.py", line 516, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/coding/variables.py", line 69, in __array__
    return self.func(self.array)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/coding/variables.py", line 135, in _apply_mask
    data = np.asarray(data, dtype=dtype)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/indexing.py", line 516, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 65, in __getitem__
    self._getitem)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/indexing.py", line 784, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 76, in _getitem
    array = getitem(original_array, key)
  File "netCDF4/_netCDF4.pyx", line 4351, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 5384, in netCDF4._netCDF4.Variable._get
  File "netCDF4/_netCDF4.pyx", line 4044, in netCDF4._netCDF4.Variable.dimensions.__get__
  File "netCDF4/_netCDF4.pyx", line 3976, in netCDF4._netCDF4.Variable._getdims
  File "netCDF4/_netCDF4.pyx", line 1857, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

```

**Comment by nsoontie** [comment]
I find it odd that the mercator.py is being called. Isn't the mercator class for datasets with dimensions latitude/longitude?

Is it possible there was a mistake with the creation of the sqlite file?

**Comment by Ocean-Navigator** [comment]
Resolved.
